name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: nixos-runners
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          # TODO: I think https://nix.dev/manual/nix/2.24/command-ref/conf-file.html#conf-ssl-cert-file
          extra_nix_config: |
            trusted-public-keys = ncps.thecluster.lan:D8fcKW2/D+zjKOABa3bDjEe8x+EPZpXnBDm+XwtNrhI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://ncps.thecluster.lan https://cache.nixos.org/

      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: unstoppablemango
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # This build is a bit too chonky for GitHub Actions to handle reliably
      - if: false
        run: nix build .#nixosConfigurations.hades.config.system.build.toplevel

      - run: nix flake check --all-systems
